name: Deploy BIM to Fabric

on:
  push:
    branches:
      - main
    paths:
      - 'DND - new copy.bim'  # Runs only when this file changes
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  deploy_bim:
    runs-on: windows-latest  # Required for PowerShell deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PowerShell Modules
        run: |
          Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser
          Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
          Install-Module -Name SqlServer -Force -Scope CurrentUser -AllowClobber

      # - name: Uninstall AzureRM Module (if exists)
      #   run: |
      #     Uninstall-Module -Name AzureRM -Force -Scope CurrentUser

      - name: Deploy BIM to Fabric
        run: |
          $ClientId = "cbc0c5f3-0578-4fc8-9be8-43392c766f61"
          $ClientSecret = "ErN8Q~r6i-WYqsUi-uwOIWg.OJmSax-mGciv1cQi"
          $TenantId = "e4d98dd2-9199-42e5-ba8b-da3e763ede2e"
          $WorkspaceName = "Tungsten Automation"
          $XmlaEndpoint = "powerbi://api.powerbi.com/v1.0/myorg/Tungsten Automation"

          # Convert Client Secret to Secure String
          $SecurePassword = ConvertTo-SecureString -String $ClientSecret -AsPlainText -Force
          $Credential = New-Object System.Management.Automation.PSCredential($ClientId, $SecurePassword)

          # Authenticate to Power BI using Service Principal
          Import-Module Az
          $AzAccount = Connect-AzAccount -ServicePrincipal -Tenant $TenantId -Credential $Credential

          # Obtain Access Token for Power BI
          $AccessToken = (Get-AzAccessToken -ResourceUrl "https://analysis.windows.net/powerbi/api").Token

          # Deploy BIM using Invoke-ASCmd
          $BimFileContent = Get-Content -Raw -Path "DND - new copy.bim"
          $Command = @"
          {
            "createOrReplace": {
              "object": {
                "database": "DND - new copy"
              },
              "json": $BimFileContent
            }
          }
          "@

          Invoke-ASCmd -Server $XmlaEndpoint -AccessToken $AccessToken -Query $Command
