name: Deploy BIM file

on:
  push:
    paths:
      - 'DND - new copy.bim'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Authenticate with Azure using Service Principal
      run: |
        az login --service-principal -u cbc0c5f3-0578-4fc8-9be8-43392c766f61 -p ErN8Q~r6i-WYqsUi-uwOIWg.OJmSax-mGciv1cQi --tenant e4d98dd2-9199-42e5-ba8b-da3e763ede2e

    - name: Deploy BIM file
      run: |
        # Custom deployment script or command here
        echo "Deploying DND - new copy.bim to the Fabric workspace..."
        # Example deployment command
        # ./deploy-bim.sh "DND - new copy.bim"

      env:
        FABRIC_WORKSPACE: your-fabric-workspace-id
        AUTH_TOKEN: your-auth-token
